// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snzhwsferlxvmoqzlxlu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuemh3c2Zlcmx4dm1vcXpseGx1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzg5ODAsImV4cCI6MjA2NDcxNDk4MH0.rITe6vxxUg2b53YUFp6b9gI7WPISwHTHi4X-L5X9TmY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);